export default [{
  name: 'Entropy',
  artist: 'Alex Skrindo',
  cover: require('./Entropy.jpg'),
  audio: require('./Entropy.mp3'),
},
{
  name: 'Jumbo',
  artist: 'Alex Skrindo',
  cover: require('./Jumbo.jpg'),
  audio: require('./Jumbo.mp3'),
},
{
  name: 'C U Again',
  artist: 'Cartoon',
  cover: require('./C_U_Again.jpg'),
  audio: require('./C_U_Again.mp3'),
},
{
  name: 'On & On',
  artist: 'Cartoon',
  cover: require('./On__On.jpg'),
  audio: require('./On__On.mp3'),
},
{
  name: 'Why We Lose',
  artist: 'Cartoon',
  cover: require('./Why_We_Lose.jpg'),
  audio: require('./Why_We_Lose.mp3'),
},
{
  name: 'Safe & Sound',
  artist: 'Different Heaven',
  cover: require('./Safe__Sound.jpg'),
  audio: require('./Safe__Sound.mp3'),
},
{
  name: 'Blank',
  artist: 'Disfigure',
  cover: require('./Blank.jpg'),
  audio: require('./Blank.mp3'),
},
{
  name: 'Hollah! ',
  artist: 'Disfigure',
  cover: require('./Hollah!.jpg'),
  audio: require('./Hollah!.mp3'),
},
// {
//   name: 'Rubik',
//   artist: 'Distrion',
//   cover: require('./Entropy.jpg'),
//   audio: require('./Rubik.mp3'),
// },
// {
//   name: 'Savannah',
//   artist: 'Diviners',
//   cover: require('./Entropy.jpg'),
//   audio: require('./Savannah.mp3'),
// },
// {
//   name: 'Tropic Love (Original Mix)',
//   artist: 'Diviners',
//   cover: require('./Entropy.jpg'),
//   audio: require('./Tropic_Love_(Original_Mix).mp3'),
// },
// {
//   name: 'My Heart',
//   artist: 'EH!DE',
//   cover: require('./Entropy.jpg'),
//   audio: require('./My_Heart.mp3'),
// },
// {
//   name: 'Symbolism',
//   artist: 'Electro-Light',
//   cover: require('./Entropy.jpg'),
//   audio: require('./Symbolism.mp3'),
// },
// {
//   name: 'Panda',
//   artist: 'Itro',
//   cover: require('./Entropy.jpg'),
//   audio: require('./Panda.mp3'),
// },
// {
//   name: 'Eclipse ',
//   artist: 'Jim Yosef',
//   cover: require('./Entropy.jpg'),
//   audio: require('./Eclipse.mp3'),
// },
// {
//   name: 'Dream Of Something Sweet',
//   artist: 'K-391',
//   cover: require('./Entropy.jpg'),
//   audio: require('./Dream_Of_Something_Sweet.mp3'),
// },
// {
//   name: 'Earth',
//   artist: 'K-391',
//   cover: require('./Entropy.jpg'),
//   audio: require('./Earth.mp3'),
// },
// {
//   name: 'Saved Me Now',
//   artist: 'Matthew Blake',
//   cover: require('./Entropy.jpg'),
//   audio: require('./Saved_Me_Now.mp3'),
// },
// {
//   name: 'Puzzle',
//   artist: 'RetroVision',
//   cover: require('./Entropy.jpg'),
//   audio: require('./Puzzle.mp3'),
// },
// {
//   name: 'Feel Good',
//   artist: 'Syn Cole',
//   cover: require('./Entropy.jpg'),
//   audio: require('./Feel_Good.mp3'),
// },
// {
//   name: 'Superhero',
//   artist: 'Unknown Brain',
//   cover: require('./Entropy.jpg'),
//   audio: require('./Superhero.mp3'),
// },
// {
//   name: 'Forever',
//   artist: 'Vanze',
//   cover: require('./Entropy.jpg'),
//   audio: require('./Forever.mp3'),
// },
// {
//   name: 'We Are',
//   artist: 'Whales',
//   cover: require('./Entropy.jpg'),
//   audio: require('./We_Are.mp3'),
// },
// {
//   name: 'Adventure (feat. Alexa Lusader)',
//   artist: 'William Ekh',
//   cover: require('./Entropy.jpg'),
//   audio: require('./Adventure_(feat._Alexa_Lusader).mp3'),
// }
];
